---

## FIXME! or ssl ?
#- command: "rsync -ci {{ misp_rootdir }}/INSTALL/apache.misp.ssl {{ apache_sitedir }}/misp-ssl.conf"
- command: "rsync -ci {{ misp_rootdir }}/INSTALL/apache.misp.ubuntu {{ apache_sitedir }}/misp.conf"
  register: rsync_result
  changed_when: 'rsync_result.stdout != ""'
  notify:
    - restart webserver

- name: redhat | update log path
  replace: "dest={{ apache_sitedir }}/misp.conf regexp='/var/log/apache2/' replace='{{ apache_logs }}/'"
  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- file: dest="{{ apache_sitedir }}/misp.conf" mode=0644
- file: dest=/etc/apache2/sites-enabled/000-default.conf state=absent
  notify:
    - restart webserver
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- file: "src={{ apache_sitedir }}/misp.conf dest=/etc/apache2/sites-enabled/misp.conf state=link"
  notify:
    - restart webserver
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: debian | ensure mod_rewrite is present
  apache2_module: state=present name=rewrite
  notify:
    - restart webserver
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

