---

- name: define composer.json to use composer install module
  copy: src=composer.json dest={{ misp_rootdir }}/app/composer.json mode=0644

## FIXME! no better way to do that?
- name: Download Composer installer.
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    mode: 0755
    sha256sum: 2d24e7ceb1144fa60b6ad4e78f572a07f676868036730e1de86135abd0783398

- name: install composer
  shell: "php -q /tmp/composer-installer.php --install-dir=/usr/local/bin --filename=composer"
  args:
    creates: /usr/local/bin/composer

- name: install PHP dependencies via composer (kamisama/cake-resque, Vendor)
  composer: command=install working_dir={{ misp_rootdir }}/app

