---
# debian wheezy: add backports
# deb http://http.debian.net/debian wheezy-backports main

- name: apt | MISP dependencies install
  apt:
    name: "{{ misp_pkg_list + webserver }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  async: 3600
  poll: 300
