---
# debian wheezy: add backports
# deb http://http.debian.net/debian wheezy-backports main

- name: apt | MISP dependencies install
  apt: name={{item}} state=present update_cache=yes cache_valid_time=3600
  with_items:
    - "{{ misp_pkg_list }}"
    - "{{ webserver }}"
  async: 3600
  poll: 300

