---
# https://github.com/MISP/MISP/blob/2.4/INSTALL/INSTALL.rhel7.txt#L368

- name: Install lief with pip
  pip:
    name: lief
    state: present
    virtualenv: "{{ misp_virtualenv }}"
    virtualenv_python: "{{ python3_bin }}"
  when: >
    ansible_os_family == 'Debian' or
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int >= 8)
  register: pkg_result
  until: pkg_result is success
  become: yes
  become_user: "{{ www_user }}"

- block:
    - name: Ensure LIEF build dependencies are present
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - centos-release-scl
        - cmake
# https://wiki.centos.org/SpecialInterestGroup/SCLo/CollectionsList
        - devtoolset-7
        - cmake3
      register: pkg_result
      until: pkg_result is success

    - name: check if LIEF present
      stat: path={{ misp_lief_rootdir }}/include/LIEF
      register: l
    - name: git clone LIEF - Library to Instrument Executable Formats
      git:
        repo: https://github.com/lief-project/LIEF.git
        dest: "{{ misp_lief_rootdir }}"
        version: "{{ misp_lief_version | default('0.10.1') }}"
        update: no
        force: no
      when: not l.stat.exists

    - name: Ensure LIEF build dir present
      file:
        dest: "{{ misp_lief_rootdir }}/build"
        state: directory

    - name: Build LIEF - Makefile
      command: >
        scl enable devtoolset-7 rh-python36 "bash -c \"cmake3 -DLIEF_PYTHON_API=on -DLIEF_DOC=off \
                -DCMAKE_INSTALL_PREFIX=$LIEF_INSTALL -DCMAKE_BUILD_TYPE=Release \
                -DPYTHON_VERSION=3.6 ..\""
      args:
        creates: "{{ misp_lief_rootdir }}/build/Makefile"
        chdir: "{{ misp_lief_rootdir }}/build"

# FIXME! can stop around 85% with
#   c++: internal compiler error: Killed (program cc1plus)
#   => replay and check that you have enough memory
    - name: Build LIEF - make
      command: 'make -j3'
      args:
        creates: "{{ misp_lief_rootdir }}/build/api/python/_pylief.so"
        chdir: "{{ misp_lief_rootdir }}/build"
      async: 3600
      poll: 0
      register: liefbuild

    - name: Build LIEF - check on async task for build
      async_status:
        jid: "{{ liefbuild.ansible_job_id }}"
      register: job_result
      until: job_result.finished or liefbuild.finished
      retries: 30
      delay: 60
      when: liefbuild is changed

    - name: Ensure pip cache permissions are correct
      file:
        dest: /usr/share/httpd/.cache/pip/http
        state: directory
        mode: '0755'
        owner: "{{ www_user }}"

    - name: Install LIEF python bindings
      pip:
        name: "file://{{ misp_lief_rootdir }}/build/api/python/lief_pybind11-prefix/src/lief_pybind11"
        state: present
        virtualenv: "{{ misp_virtualenv }}"
        virtualenv_python: "{{ python3_bin }}"
      register: pkg_result
      until: pkg_result is success
      become: yes
      become_user: "{{ www_user }}"

    - name: Ensure updated version of pip and setuptools
      pip:
        name: "{{ item.n }}"
        version: "{{ item.v }}"
        state: present
        virtualenv: "{{ misp_virtualenv }}"
        virtualenv_python: "{{ python3_bin }}"
      register: pkg_result
      until: pkg_result is success
      become: yes
      become_user: "{{ www_user }}"
      with_items:
        - { n: pip, v: '20.0.2' }
        - { n: setuptools, v: '45.1.0' }

    - name: Install PyLIEF
      pip:
        name: https://github.com/lief-project/packages/raw/lief-master-latest/pylief-0.9.0.dev.zip
        state: present
        virtualenv: "{{ misp_virtualenv }}"
        virtualenv_python: "{{ python3_bin }}"
      register: pkg_result
      until: pkg_result is success
      become: yes
      become_user: "{{ www_user }}"

    - name: Install LIEF
      command: "{{ item.c }}"
      args:
        creates: "{{ item.t }}"
        chdir: "{{ misp_lief_rootdir }}/build"
      with_items:
        - { c: 'make install', t: '/share/LIEF/examples/c/elf_reader.c' }
        - { c: 'make package', t: '/var/lief/build/LIEF-0.9.0-Linux.tar.gz' }

  when: >
    (ansible_os_family == "RedHat" and ansible_distribution_major_version|int < 8)

# FIXME! pip install fails on centos7. https://www.centos.org/forums/viewtopic.php?t=66248
#   ImportError: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found
#        (required by /usr/lib64/python2.7/site-packages/_pylief.so)
#   $ strings /usr/lib64/libstdc++.so.6.0.19 | grep GLIBCXX
#   ? /opt/rh/devtoolset-7/root/usr/lib/gcc/x86_64-redhat-linux/7/libstdc++.so
- name: Ensure LIEF is working
  command: "python -c 'import lief'"
  environment:
    PATH: "{{ misp_virtualenv }}/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
  ignore_errors: true
  changed_when: false
