---

- name: flush handlers as we need service up for API call
  meta: flush_handlers

## FIXME! not idempotent, no way to list feeds with their status
- name: enable feeds
  uri:
    url: "{{ misp_base_url }}/feeds/enable/{{ item }}"
    method: POST
    HEADER_Authorization: "{{ userkey }}"
    HEADER_Accept: application/json
    HEADER_Content-Type: application/json
  with_items: "{{ misp_enable_feeds }}"
  register: enableresults
#- debug: var=enableresults

- name: disable feeds
  uri:
    url: "{{ misp_base_url }}/feeds/disable/{{ item }}"
    method: POST
    HEADER_Authorization: "{{ userkey }}"
    HEADER_Accept: application/json
    HEADER_Content-Type: application/json
  with_items: "{{ misp_disable_feeds }}"
  register: disableresults
#- debug: var=disableresults
