---
## https://github.com/MISP/misp-modules

- stat: path={{ mispmodules_rootdir }}/misp-modules
  register: mm
- name: git clone MISP modules
  git: repo=https://github.com/MISP/misp-modules.git
       dest={{ mispmodules_rootdir }}/misp-modules
  when: not mm.stat.exists

- name: debian | install dependencies for MISP modules (pip3)
  pip: requirements={{ mispmodules_rootdir }}/misp-modules/REQUIREMENTS executable=pip3
  when: ansible_os_family == 'Debian'
## centos7: pip points to python34
- name: redhat | install dependencies for MISP modules (pip3)
  pip: requirements={{ mispmodules_rootdir }}/misp-modules/REQUIREMENTS executable=pip
  when: ansible_os_family == 'RedHat'

- name: install MISP modules (pip3)
  pip: name=file://{{ mispmodules_rootdir }}/misp-modules executable=pip3

- name: add MISP modules script for boot
  lineinfile:
    dest: /etc/rc.local
    regexp: "sudo -H -u {{ www_user }} misp-modules .* &"
    line: "sudo -H -u {{ www_user }} misp-modules -s > /tmp/misp-modules.boot 2>&1 &"
    insertbefore: "^exit 0"
    backup: yes

- name: check if misp modules is running
  shell: "ps axu |grep misp-modules"
  register: ps
  changed_when: false
  ignore_errors: true
- name: start MISP modules app
  shell: "misp-modules -s > /tmp/misp-modules.start 2>&1 &"
  become: yes
  become_user: "{{ www_user }}"
  when: "'misp-modules' not in ps.stdout"

- name: Redhat7 | libpcre symlink for python yara module
  file:
    src: /usr/lib64/libpcre.so.1
    dest: /usr/lib64/libpcre.so.3
    state: link
  when: ansible_os_family == "RedHat" and ansible_distribution_version.split('.')[0] == '7'

- name: Ubuntu | libyara.so symlink for python yara module
  file:
    src: "{{ mispmodules_libyarapath }}/libyara.so"
    dest: /usr/lib/libyara.so
    state: link
  when: ansible_os_family == "Ubuntu"
