---

- name: creating mysql misp db
  mysql_db: name=misp state=present
- stat: path=/root/.mysql_misp_imported
  register: mispdbloaded
- name: importing mysql misp db template
  mysql_db: name=misp state=import target={{ misp_rootdir }}/INSTALL/MYSQL.sql
  when: not mispdbloaded.stat.exists
- file: dest=/root/.mysql_misp_imported state=touch
  when: not mispdbloaded.stat.exists
- name: creating mysql misp db user
  mysql_user: name="{{ misp_db_user }}" password="{{ misp_db_pass }}" priv=*.*:USAGE/misp.*:ALL state=present

