---

- name: yum | remi yum-utils
  yum: name=yum-utils state=present update_cache=yes

## for php-redis
- include: redhat-remi.yml

- name: yum | MISP dependencies install
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - "{{ misp_pkg_list }}"
    - "{{ webserver }}"
  async: 3600
  poll: 300

- block:
    - name: set php-fpm to use socket file
      replace: "dest=/etc/php-fpm.d/www.conf regexp={{ item.re }} replace={{ item.rep }} backup=yes"
      with_items:
        - { re: '^listen = .*$', rep: 'listen = /var/run/php-fpm/php-fpm.sock' }
        - { re: '^;listen.owner = nobody', rep: 'listen.owner = {{ fpm_user }}' }
        - { re: '^;listen.group = nobody', rep: 'listen.group = {{ fpm_user }}' }
        - { re: '^listen.owner = .*$', rep: 'listen.owner = {{ fpm_user }}' }
        - { re: '^listen.group = .*$', rep: 'listen.group = {{ fpm_user }}' }
      notify:
        - restart php-fpm

    - name: ensure socket dir exists
      file: dest=/var/run/php-fpm state=directory owner=nobody group=nobody mode=0755

    - name: set php-fpm user/group to nginx
      replace: "dest=/etc/php-fpm.d/www.conf regexp={{ item.re }} replace={{ item.rep }} backup=yes"
      with_items:
        - { re: '^user = .*$', rep: 'user = nginx' }
        - { re: '^group = .*$', rep: 'group = nginx' }
      notify:
        - restart php-fpm
  when: misp_webserver is defined and misp_webserver == 'nginx'

## http://stackoverflow.com/questions/32618686/how-to-install-pip-in-centos-7
- name: redhat | install missing pip3 command
  command: "easy_install-3.4 pip creates=/usr/bin/pip3"

# https://github.com/ansible/ansible/issues/16612
- block:
    - debug: var=ansible_selinux
    - name: RedHat | Ensure selinux dependencies are present
      package:
        name: libselinux-python
        state: present
    - action: setup
    - debug: var=ansible_selinux
  when: ansible_os_family == "RedHat"
- block:
    - name: RedHat | Ensure selinux dependencies are present
      package:
        name: "{{ item }}"
        state: present
      with_items:
        - libselinux-python
        - libsemanage-python
        - policycoreutils-python

    - name: RedHat | Allow proxy to network connect in selinux
      seboolean:
        name: httpd_can_network_connect
        state: yes
        persistent: yes

# https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/6/html/Managing_Confined_Services/sect-Managing_Confined_Services-Configuration_examples-Changing_port_numbers.html
# https://wiki.centos.org/HowTos/SELinux#head-ad837f60830442ae77a81aedd10c20305a811388
    - name: RedHat | Allow httpd to listen to unusual ports
      seport:
        ports: "{{ misp_base_port }}"
        proto: tcp
        setype: http_port_t
        state: present
      when: misp_base_port != 80 and misp_base_port != 443
  when: ansible_os_family == "RedHat" and ansible_selinux.status is defined and ansible_selinux.status != 'disabled'

- name: Ensure misp web logs are rotated
  copy:
    src: "{{ misp_rootdir }}/INSTALL/misp.logrotate"
    dest: "/etc/logrotate.d/misp"
    mode: '0644'
    remote_src: true
    backup: yes

- name: Ensure misp web logs have right selinux context for rotation
  sefcontext:
    target: "{{ misp_rootdir }}/app/tmp/logs(/.*)?"
    setype: httpd_log_t
    state: present

- name: Allow logrotate to read /var/www
  command: "{{ item.c }}"
  args:
    creates: "{{ item.t }}"
  with_items:
    - { c: "checkmodule -M -m -o /root/misplogrotate.mod {{ misp_rootdir }}/INSTALL/misplogrotate.te", t: "/root/misplogrotate.mod" }
    - { c: "semodule_package -o /root/misplogrotate.pp -m /root/misplogrotate.mod", t: "/root/misplogrotate.pp" }
    - { c: "semodule -i /root/misplogrotate.pp", t: "/tmp/doesnotexist" }
