---

- name: yum | remi yum-utils
  yum: name=yum-utils state=present update_cache=yes

## for php-redis
- include: redhat-remi.yml

- name: yum | MISP dependencies install
  yum: name={{item}} state=present update_cache=yes
  with_items:
    - "{{ misp_pkg_list }}"
    - "{{ webserver }}"
  async: 3600
  poll: 300

- block:
    - name: set php-fpm to use socket file
      replace: "dest=/etc/php-fpm.d/www.conf regexp={{ item.re }} replace={{ item.rep }} backup=yes"
      with_items:
        - { re: '^listen = .*$', rep: 'listen = /var/run/php-fpm/php-fpm.sock' }
        - { re: '^;listen.owner = nobody', rep: 'listen.owner = {{ fpm_user }}' }
        - { re: '^;listen.group = nobody', rep: 'listen.group = {{ fpm_user }}' }
        - { re: '^listen.owner = .*$', rep: 'listen.owner = {{ fpm_user }}' }
        - { re: '^listen.group = .*$', rep: 'listen.group = {{ fpm_user }}' }
      notify:
        - restart php-fpm

    - name: ensure socket dir exists
      file: dest=/var/run/php-fpm state=directory owner=nobody group=nobody mode=0755

    - name: set php-fpm user/group to nginx
      replace: "dest=/etc/php-fpm.d/www.conf regexp={{ item.re }} replace={{ item.rep }} backup=yes"
      with_items:
        - { re: '^user = .*$', rep: 'user = nginx' }
        - { re: '^group = .*$', rep: 'group = nginx' }
      notify:
        - restart php-fpm
  when: misp_webserver is defined and misp_webserver == 'nginx'

## http://stackoverflow.com/questions/32618686/how-to-install-pip-in-centos-7
- name: redhat | install missing pip3 command
  command: "easy_install-3.4 pip creates=/usr/bin/pip3"

