---
# https://redis.io/topics/security
# https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-18-04

- name: redis | require password
  lineinfile:
    dest: "{{ redis_conf }}"
    regexp: '^requirepass .*'
    line: "requirepass {{ misp_redis_password }}"
    backup: yes
  when: misp_redis_password is defined and misp_redis_password != ''

- name: redis | rename dangerous commands
  lineinfile:
    dest: "{{ redis_conf }}"
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
  with_items: "{{ misp_redis_securecommands }}"
  when: misp_redis_securecommands is defined and misp_redis_securecommands != []
