---
# https://redis.io/topics/security
# https://www.digitalocean.com/community/tutorials/how-to-secure-your-redis-installation-on-ubuntu-18-04

- name: redis | require password
  lineinfile:
    dest: /etc/redis.conf
    regexp: '^requirepass .*'
    line: "requirepass {{ misp_redis_password }}"
    backup: yes

- name: redis | rename dangerous commands
  lineinfile:
    dest: /etc/redis.conf
    regexp: "{{ item.re }}"
    line: "{{ item.l }}"
  with_items: "{{ misp_redis_securecommands }}"
