---
- name: restart webserver
  service: name={{ apache_svc }} state=restarted
  when: not (ansible_virtualization_type is defined and ansible_virtualization_type == "docker")

- name: restart php-fpm
  service: name=php-fpm state=restarted

- name: restart rng-tools
  service: name=rng-tools state=restarted

- name: updating existing MISP submodules - minor releases
  command: "git submodule update --init --force"
  args:
    chdir: "{{ misp_rootdir }}"
